= DE10-Lite ADC Projects

Projects using the onboard ADC of the https://www.terasic.com.tw/cgi-bin/page/archive.pl?Language=English&CategoryNo=234&No=1021[DE10-Lite board] from Terasic.

The DE10-Lite board is equipped with a MAX10DA50 device. This device has two onboard 12-bit, 1 Msps, ADCs but only the first ADC is connected to external pins. The pins of the second ADC are all connected to GND.

The ADC has one dedicated analog input and eight dual digital/analog pins. The first ADC is also connected to the onboard temperature sensor.

The dedicated analog input (channel 0) is connected to GND and is therefore not usable. Channels 1 to 6 are usable. They are connected to Arduino analog inputs A0 to A5. Channel 17 is connected to the temperature sensor. Other channel numbers are not usable.

The maximum input voltage on the ADC inputs is 5V. The input voltages are fed to a front-end circuit which halves the input voltage (2.5V is the maximun input voltage of the ADC) and has a low pass filter (anti-alias filter) with a cut-off frequency of 500 kHz.

For online reference, see https://docs.altera.com/r/docs/683596/24.1/max-10-analog-to-digital-converter-user-guide/max-10-analog-to-digital-converter-overview[the analog user guide].

